config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  root 'quotes#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :body, presence: true,  length: {minimum: 5}
  validates :author, presence: true,  length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  
  def index
    @quotes = Quote.all
  end
  
  def new
    @quote = Quote.new
  end
  
  def edit
    @quote = Quote.find(params[:id])
  end
  
  def create
    @quote = Quote.new(quote_params)
    if @quote.save
      flash[:success] = "New quote saved!"
      redirect_to @quote
    else
      flash[:error] = "There was an error!"
      render :new
    end
  end
  
  def update
    @quote = Quote.find(params[:id])
    if @quote.update(quote_params)
      flash[:success] = "Quote Updated!"
      redirect_to @quote
    else
      flash[:error] = "There was an error!"
      render :edit
    end
  end
  
  def show
    @quote = Quote.find(params[:id])
  end
  
  def quote_params
    params.require(:quote).permit(:body, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuotesAndVotes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<%= yield %>

</body>
</html>

app/views/quotes/edit.html.erb
<%= form_for @quote, url: {action: "update"} do |f| %>
  
  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.label :author %>
  <%= f.text_field :author %>
  
  <%= f.submit "Submit" %>

<% end %>

app/views/quotes/index.html.erb
<h1>Index</h1>

<%= link_to "New Quote", new_quote_path %>

<h4>QUOTES:</h4>

<% @quotes.each do |quote| %>
  <p><%= quote.body %></p>
  <p><%= quote.author %></p>
  <p><%= link_to "See quote", quote_path(quote) %></p>
<% end %>

app/views/quotes/new.html.erb
<%= form_for @quote, url: {action: "create"} do |f| %>
  
  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.label :author %>
  <%= f.text_field :author %>
  
  <%= f.submit "Submit" %>

<% end %>

app/views/quotes/show.html.erb
<%= @quote.body %>
<%= @quote.author %>
<%= link_to "Edit", edit_quote_path %>